// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4PW3Hns7GxKYe7XfyqBQxCf1G0VtNq4',
    appId: '1:254389889576:web:49d1a44fc45e0062a0631d',
    messagingSenderId: '254389889576',
    projectId: 'women-94051',
    authDomain: 'women-94051.firebaseapp.com',
    storageBucket: 'women-94051.appspot.com',
    measurementId: 'G-PGFDSYPXDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSF9szsZKC3IEqkIFIuVLhy8NZl1Rfk4E',
    appId: '1:254389889576:android:3d6ac92d4c6b5e16a0631d',
    messagingSenderId: '254389889576',
    projectId: 'women-94051',
    storageBucket: 'women-94051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAafVeMBmD9Z2rjiRQIDhZ09RG6CxBjFnE',
    appId: '1:254389889576:ios:3a63537bada7039da0631d',
    messagingSenderId: '254389889576',
    projectId: 'women-94051',
    storageBucket: 'women-94051.appspot.com',
    iosBundleId: 'com.example.secureVoyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAafVeMBmD9Z2rjiRQIDhZ09RG6CxBjFnE',
    appId: '1:254389889576:ios:3a63537bada7039da0631d',
    messagingSenderId: '254389889576',
    projectId: 'women-94051',
    storageBucket: 'women-94051.appspot.com',
    iosBundleId: 'com.example.secureVoyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK4PW3Hns7GxKYe7XfyqBQxCf1G0VtNq4',
    appId: '1:254389889576:web:c1b56880916f6ee9a0631d',
    messagingSenderId: '254389889576',
    projectId: 'women-94051',
    authDomain: 'women-94051.firebaseapp.com',
    storageBucket: 'women-94051.appspot.com',
    measurementId: 'G-LKYP2HJQFD',
  );

}